In [1]:
#Build a method to build and visualize the grid filled with random numbers.
import random
import numpy as np

In [2]:
HEIGHT = int(input("Insert amount of rows in the grid "))
WIDTH = int(input("Insert amount of columns in the grid "))

Insert amount of rows in the grid 8
Insert amount of columns in the grid 8


In [3]:
ARRAY = np.random.randint(0,9, (HEIGHT, WIDTH))
print(ARRAY)

[[4 3 3 2 1 2 2 2]
 [7 8 0 8 3 5 5 0]
 [3 2 5 5 8 5 5 5]
 [6 4 4 3 3 1 0 4]
 [3 7 5 0 4 3 4 4]
 [7 3 8 0 5 1 5 0]
 [0 4 4 5 0 0 6 7]
 [8 8 7 1 7 4 5 6]]


In [4]:
[8, 2, 3, 3, 1, 4, 5, 4, 3, 4, 1, 1, 4, 0, 5, 7, 5]

[8, 2, 3, 3, 1, 4, 5, 4, 3, 4, 1, 1, 4, 0, 5, 7, 5]

In [5]:
#finding neihbour in the grid for each cell
#agent moves from cell to cell (u,d,l,r)
def f_neighbours(array, i, j):
    neighbours_k = []
    neighbours_v = []
    while True:
        if i >= HEIGHT or j >= WIDTH:
            False
            
        #neighbors search goes cloclwise:
        elif i == 0 or i == (HEIGHT-1) or j == 0 or j == (WIDTH - 1):    # corners and sides
            
            if i != 0:
                neighbours_k.append(array[i - 1, j])
                neighbours_v.append((i - 1,j)) # u
                
            if j != (WIDTH - 1):             
                neighbours_k.append(array[i, j+1])
                neighbours_v.append((i, j+1))#r
                
            if i != (HEIGHT-1):
                neighbours_k.append(array[i+1,j])
                neighbours_v.append((i+1, j))#d
                                    
#             if j != 0:                  
#                 neighbours_k.append(array[i, j-1]) # l
#                 neighbours_v.append((i,j - 1)) 
                

        elif i < HEIGHT and j < WIDTH:
            neighbours_k = [array[i - 1, j], array[i, j + 1], array[i + 1, j]]  #, array[i, j - 1]]
            neighbours_v = [(i - 1,j), (i,j + 1), (i + 1,j)] #(i,j - 1)
        return neighbours_k, neighbours_v


# neighbours = f_neighbours(array=ARRAY, i=2,j=1)
# # neighbours = neighbours(ARRAY, 0, 0)
# print(neighbours)
# type(neighbours)
# ks= neighbours[0]
# vs = neighbours[1]
# print(ks)
# print(vs)

In [6]:
ks = [1, 3, 0, 3]

def f_cell (ks):
    min_val=min(ks)
    return min_val
        
# a = f_min(ks)
# print(a)


In [7]:
def f_location (ks, a):
    location = ks.index(a)
    return location

In [8]:
# find the row i position
def first(vs, idex_pos):
    location = vs[idex_pos]
#     print(location)
    i = location[0]
    return i


# i = first(neighbours, cell)
# print(i)
# print(type(i))

In [9]:
# find the column j position
def second (vs, idex_pos):
    location = vs[idex_pos]
    j = location[1]
    return j

# j = second(neighbours, cell)
# print(j)
# print(type(j))END = ARRAY[HEIGHT - 1, WIDTH - 1]

In [10]:
# test game
game_is_on = True

score = []

next_cell = ARRAY[0, 0]
score.append(next_cell)
neighbours = {next_cell: (0, 0)}

prev_cell = ARRAY[0, 0]
prev_l = [(0, 0)]

i=0
j=0

In [37]:
while game_is_on:

    neighbours = f_neighbours(ARRAY, i, j) #finds all neighbours
    ks= neighbours[0]
    vs = neighbours[1]
   
    print(ks)
    print(vs)
    if (HEIGHT-1, WIDTH-1) in vs:
        next_cell = ARRAY[HEIGHT-1, WIDTH-1]
        game_is_on = False
    
    else:
        next_cell = f_cell(ks) #finding the minimum value cell
        index_pos = f_location(ks, next_cell)
    
    #if the smallest one  - the previous one, chose the other smallest
    if vs[index_pos] in prev_l:
        ks.remove(next_cell)
        del(vs[index_pos])
        next_cell = f_cell(ks)
        index_pos = f_location(ks, next_cell)


    score.append(next_cell)

    prev_cell=next_cell
    prev_l.append(vs[index_pos])

    i = first(vs, index_pos)
    j = second(vs, index_pos)
    
    #if next_cell is our destination cell then the program stops
    if vs[index_pos] == (HEIGHT-1, WIDTH-1):
        game_is_on = False
        
print(score)
len(score)

[4, 3, 3, 0, 5, 4, 3, 0, 0, 5, 0, 0, 1, 3, 1, 0, 4, 4, 0, 7, 0]


21

In [16]:
total = sum(score)  #sum of the list with weight of each step
print (f"End of the game. Your final score is {total}")

End of the game. Your final score is 47


In [36]:
print(prev_l)
len(prev_l)

[(0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (3, 2), (3, 3), (4, 3), (5, 3), (5, 4), (6, 4), (6, 5), (5, 5), (4, 5), (3, 5), (3, 6), (3, 7), (4, 7), (5, 7), (6, 7), (7, 7)]


21

In [26]:
from statistics import median
list_new = [score[0],score[1]]
m=median(list_new)
print (m)

3.5


In [27]:
median_list =[]
median_list.append(m)
print(median_list)

[3.5]
